name: lhm
up:
  - homebrew:
      - mysql-client@5.7:
          or: [mysql@5.7]
          conflicts: [shopify/shopify/mysql-client, mysql-connector-c, mysql, mysql-client]
      - wget
  - ruby
  - bundler
  - podman
  - custom:
      name: Get Appraisal gems
      met?: bundle exec appraisal install
      meet: ":"
  - custom:
      name: Podman compose
      met?: podman-compose ps | grep -ioE -q "lhm.*running\(4\)"
      meet: podman-compose up -d
  - custom:
      name: Waiting for DBs to be operational
      met?: ./scripts/helpers/wait-for-dbs.sh
      meet: ":"

commands:
  unit: bundle exec rake unit
  int: bundle exec rake integration
  test:
    syntax:
      optional: file
    aliases: [ t ]
    run: |
      if [[ $# -eq 0 ]]; then
        bundle exec rake unit && bundle exec rake integration
      else
        SINGLE_TEST="$@" bundle exec rake dev
      fi
  appraisals: bundle exec appraisal rake specs
  cov: rm -rf coverage; COV=1 bundle exec rake unit && bundle exec rake integration; open coverage/index.html
  logs:
    desc: "See the DB logs (ctrl-c + ctrl-c to exit)"
    run: podman-compose logs -f
  clear:
    run: podman-compose down -v && podman-compose up -d && ./scripts/helpers/wait-for-dbs.sh
    subcommands:
      mysql-5.7: podman-compose down -v && podman-compose -f docker-compose-mysql-5.7.yml up -d && ./scripts/helpers/wait-for-dbs.sh
      mysql-8.0: podman-compose down -v && podman-compose -f docker-compose-mysql-8.0.yml up -d && ./scripts/helpers/wait-for-dbs.sh
  pre-publish:
    # Ensures all Gemfile.lock are sync with the new version in `lhm/version.rb` and runs appraisals
    run: bundle install && bundle exec appraisal install && bundle exec appraisal rake specs
