name: Liquid
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        include:
          - { ruby: '3.0', allowed-failure: false }
          - { ruby: '3.1', allowed-failure: false }
          - { ruby: '3.2', allowed-failure: false }
          - { ruby: '3.3', allowed-failure: false }
          - { ruby: ruby-head, allowed-failure: true }
          - { ruby: truffleruby-head, allowed-failure: true }
    name: test (${{ matrix.ruby }})
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: bundle exec rake
        continue-on-error: ${{ matrix.allowed-failure }}
        env:
          LIQUID_C_PEDANTIC: 'true'
        if: matrix.ruby != 'truffleruby-head'

      - run: bundle exec rake test:unit
        continue-on-error: ${{ matrix.allowed-failure }}
        env:
          LIQUID_C_PEDANTIC: 'true'
          TEST_OPTS: '-v -s0'
        if: matrix.ruby == 'truffleruby-head'

      - run: bundle exec rubocop
        if: matrix.ruby != 'truffleruby-head'

  valgrind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: sudo apt-get install -y valgrind
      - run: bundle exec rake test:valgrind
