---
- name: Ruby
  autoLowLikelihood:
    - name: MIME::Types::Container implementation details
      pathStartsWith: lib/mime/types/container.rb
      allowedTerms:
        - '[]='
        - marshal_dump
        - marshal_load
        - to_hash
    - name: MIME::Types::Columnar array parser
      pathStartsWith: lib/mime/types/_columnar.rb
      allowedTerms:
        - arr
        - extended
    - name: MIME::Types::Logger close (required for implementation)
      pathStartsWith: lib/mime/types/logger.rb
      termEquals: close
    - name: MIME::Type writers
      pathStartsWith: lib/mime/type.rb
      allowedTerms:
        - content_type=
        - extensions=
    - name: MIME::Type dynamic calls
      pathStartsWith: lib/mime/type.rb
      termStartsWith: xref_url_for_
    - name: MIME::Type object implementation
      pathStartsWith: lib/mime/type.rb
      allowedTerms:
        - eql?
        - to_str
    - name: MIME::Types::Loader YAML loader (used by mime-types-data tools)
      pathStartsWith: lib/mime/types/loader.rb
      termEquals: load_yaml
    - name: MIME::Types tests
      pathStartsWith: test/
      allowedTerms:
        - around
        - teardown
