rasterizer:
  command: phantomjs
  port: 3011           # internal service port. No need to allow inbound or outbound access to this port
  path: '/tmp/'        # where the screenshot files are stored
  viewport: '1024x600' # browser window size. Height frows according to the content
cache:
  lifetime: 604800000  # one week, set to 0 for no cache
server:
  port: 3000           # main service port
  useCors: true       # enable CORS support
