inherit_gem:
  rubocop-shopify: rubocop.yml

require: rubocop-performance

AllCops:
  Exclude:
    - 'vendor/bundle/**/*'
    - 'tmp/**/*'

Style/GlobalVars:
  Exclude:
    - 'ext/liquid_c/extconf.rb'
