name: PyreferrerCI

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        version:
          - '2.7'
          - '3.4'
          - '3.5'
          - '3.6'
          - '3.7'

    name: Test Python ${{ matrix.version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.version }}
    - name: Install Dependencies
      run: |
          pip install -e '.[test]'
    - name: Run tests
      run: nosetests