language: android
sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
  licenses:
    - 'android-sdk-license-.+'
    - '.+'

jdk:
  - oraclejdk8

env:
  global:
    - GRADLE_OPTS="-Xmx2048m -XX:MaxPermSize=1024m"
    - EMULATOR_API=22 # 24 has some issues, probably some overlayed window
    - EMULATOR_ABI=x86_64 # seems to work with emulator v29.
    - EMULATOR_TAG=default # can be google_apis
    - PATH=$ANDROID_HOME:$ANDROID_HOME/emulator:$ANDROID_HOME/platform-tools:$PATH

notifications:
  email: false

git:
  submodules: false

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

install:
  # Setup
  - echo $ANDROID_HOME # We assume this is correctly set when setting path
  - sdkmanager --list || true # Look at the packages
  - echo yes | sdkmanager "tools" # Ensure tools is updated
  - echo yes | sdkmanager "emulator" # Ensure emulator is present

  # Install emulator
  # The channel=4 line looks into canary which brings in v29.
  # The previous version v28 was broken:
  # https://travis-ci.community/t/android-emulators-not-starting-for-the-last-few-days-late-march-2019/2871/11?u=mikehardy
  - export EMULATOR="system-images;android-$EMULATOR_API;$EMULATOR_TAG;$EMULATOR_ABI"
  - echo yes | sdkmanager "platforms;android-$EMULATOR_API" # Install sdk for the emulator
  - echo yes | sdkmanager --channel=4 "$EMULATOR" # Install system image
  - sdkmanager --list || true # Check everything is updated

  # Create adn start emulator
  - echo no | avdmanager create avd -n test -k "$EMULATOR" -f # Create emulator virtual device
  - which emulator # ensure we are using the right emulator ($ANDROID_HOME/emulator/emulator)
  - emulator -avd test -no-window -no-accel -no-snapshot -camera-back emulated -camera-front emulated -memory 2048 -writable-system & # Launch
  - adb wait-for-device # Wait for adb process
  - adb remount # Mount as writable

before_script:
  - cd MobileBuy
  # Wait for emulator
  - android-wait-for-emulator # Wait for emulator ready to interact
  - adb shell settings put global window_animation_scale 0 & # Disable animations
  - adb shell settings put global transition_animation_scale 0 & # Disable animations
  - adb shell settings put global animator_duration_scale 0 & # Disable animations

script:
  - ./gradlew clean build connectedCheck -PdisablePreDex --console=plain

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2/repository