inherit_from:
  - https://shopify.github.io/ruby-style-guide/rubocop.yml

AllCops:
  TargetRubyVersion: 2.2

Style/BlockDelimiters:
  Enabled: false

Style/CommandLiteral:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false
