name: mruby-engine

up:
  - ruby:
      package: shopify/shopify/shopify-ruby
      version: 2.6.2
  - bundler
  - submodules

commands:
  recompile:
    syntax: ""
    desc: "Compiles native extention"
    run: bin/rake clobber compile
  compile:
    syntax: ""
    desc: "Compiles native extention"
    run: bin/rake compile
  spec:
    syntax: ""
    desc: "Run specs"
    run: bin/rake spec
