---
http_interactions:
- request:
    method: put
    uri: https://okta-test.okta.com/api/v1/apps/0oa6nmg6fdvwvoHwR0h7/groups/00g6nm9yt5VEl6xYd0h7
    body:
      encoding: UTF-8
      string: "{}"
    headers:
      User-Agent:
      - Oktakit v0.1.0
      Accept:
      - application/json
      Content-Type:
      - application/json
      Authorization:
      - SSWS  <<ACCESS_TOKEN>>
  response:
    status:
      code: 200
      message: 
    headers:
      date:
      - Thu, 14 Jul 2016 04:30:59 GMT
      server:
      - nginx
      content-type:
      - application/json;charset=UTF-8
      vary:
      - Accept-Encoding
      x-okta-request-id:
      - V4cVg59thkP2wy3aoVKXNAAAAj8
      x-rate-limit-limit:
      - '1200'
      x-rate-limit-remaining:
      - '1199'
      x-rate-limit-reset:
      - '1468470719'
      p3p:
      - CP="HONK"
      cache-control:
      - no-cache, no-store
      pragma:
      - no-cache
      expires:
      - '0'
      strict-transport-security:
      - max-age=315360000
      set-cookie:
      - sid=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/, JSESSIONID=8CAA713A7F647324335C0546FA6BA19A;
        Path=/
      connection:
      - close
      transfer-encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"id":"00g6nm9yt5VEl6xYd0h7","lastUpdated":"2016-07-14T04:30:59.000Z","priority":0,"profile":{},"_links":{"app":{"href":"https://okta-test.okta.com/api/v1/apps/0oa6nmg6fdvwvoHwR0h7"},"self":{"href":"https://okta-test.okta.com/api/v1/apps/0oa6nmg6fdvwvoHwR0h7/groups/00g6nm9yt5VEl6xYd0h7"},"group":{"href":"https://okta-test.okta.com/api/v1/groups/00g6nm9yt5VEl6xYd0h7"}}}'
    http_version: 
  recorded_at: Thu, 14 Jul 2016 04:30:58 GMT
recorded_with: VCR 3.0.3
