http_interactions:
- request:
    method: delete
    uri: https://okta-test.okta.com/api/v1/apps/0oa6nmg6fdvwvoHwR0h7
    body:
      encoding: UTF-8
      string: "{}"
    headers:
      User-Agent:
      - Oktakit v0.1.0
      Accept:
      - application/json
      Content-Type:
      - application/json
      Authorization:
      - SSWS  <<ACCESS_TOKEN>>
  response:
    status:
      code: 204
      message: 
    headers:
      date:
      - Thu, 14 Jul 2016 04:45:09 GMT
      server:
      - nginx
      x-okta-request-id:
      - V4cY1NtnJBqDdYPiZol4lAAAC14
      x-rate-limit-limit:
      - '1200'
      x-rate-limit-remaining:
      - '1197'
      x-rate-limit-reset:
      - '1468471518'
      p3p:
      - CP="HONK"
      cache-control:
      - no-cache, no-store
      pragma:
      - no-cache
      expires:
      - '0'
      x-okta-backend:
      - op1-majorapp01b.aue1s.saasure.com
      x-frame-options:
      - SAMEORIGIN
      strict-transport-security:
      - max-age=315360000
      set-cookie:
      - sid=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/, JSESSIONID=D3C5300973B0F6B9D48E211C539FECF7;
        Path=/, JSESSIONID=D3C5300973B0F6B9D48E211C539FECF7; Path=/; Secure
      content-length:
      - '0'
      connection:
      - close
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Thu, 14 Jul 2016 04:45:09 GMT
recorded_with: VCR 2.9.3
