---
http_interactions:
- request:
    method: post
    uri: https://okta-test.okta.com/api/v1/apps/0oa6nmg6fdvwvoHwR0h7/credentials/keys/generate?validityYears=1
    body:
      encoding: UTF-8
      string: "{}"
    headers:
      User-Agent:
      - Oktakit v0.1.0
      Accept:
      - application/json
      Content-Type:
      - application/json
      Authorization:
      - SSWS  <<ACCESS_TOKEN>>
  response:
    status:
      code: 201
      message: 
    headers:
      date:
      - Thu, 14 Jul 2016 04:25:28 GMT
      server:
      - nginx
      content-type:
      - application/json
      x-okta-request-id:
      - V4cUOCGXJLimuAsnJGdNfAAABqo
      x-rate-limit-limit:
      - '1200'
      x-rate-limit-remaining:
      - '1199'
      x-rate-limit-reset:
      - '1468470388'
      p3p:
      - CP="HONK"
      cache-control:
      - no-cache, no-store
      pragma:
      - no-cache
      expires:
      - '0'
      set-cookie:
      - sid=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/, JSESSIONID=0509E2FAE7627FE5BC112C35DA9B23BB;
        Path=/
      connection:
      - close
      transfer-encoding:
      - chunked
    body:
      encoding: UTF-8
      string: '{"created":"2015-12-10T18:56:23.000Z","expiresAt":"2017-12-10T18:56:22.000Z","x5c":["MIIDqDCCApCgAwIBAgIGAVGNQFX5MA0GCSqGSIb3DQEBBQUAMIGUMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEWMBQGA1UEBwwNU2FuIEZyYW5jaXNjbzENMAsGA1UECgwET2t0YTEUMBIGA1UECwwLU1NPUHJvdmlkZXIxFTATBgNVBAMMDGJhbGFjb21wdGVzdDEcMBoGCSqGSIb3DQEJARYNaW5mb0Bva3RhLmNvbTAeFw0xNTEyMTAxODU1MjJaFw0xNzEyMTAxODU2MjJaMIGUMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEWMBQGA1UEBwwNU2FuIEZyYW5jaXNjbzENMAsGA1UECgwET2t0YTEUMBIGA1UECwwLU1NPUHJvdmlkZXIxFTATBgNVBAMMDGJhbGFjb21wdGVzdDEcMBoGCSqGSIb3DQEJARYNaW5mb0Bva3RhLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJJjrcnI6cXBiXNq9YDgfYrQe2O5qEHG4MXP8Ue0sMeefFkFEHYHnHUeZCq6WTAGqR+1LFgOl+Eq9We5V+qNlGIfkFkQ3iHGBrIALKqLCd0Et76HicDiegz7j9DtN+lo0hG/gfcw5783L5g5xeQ7zVmCQMkFwoUA0uA3bsfUSrmfORHJL+EMNQT8XIXD8NkG4g6u7ylHVRTLgXbe+W/p04m3EP6l41xl+MhIpBaPxDsyUvcKCNwkZN3aZIin1O9Y4YJuDHxrM64/VtLLp0sC05iawAmfsLunF7rdJAkWUpPn+xkviyNQ3UpvwAYuDr+jKLUdh2reRnm1PezxMIXzBVMCAwEAATANBgkqhkiG9w0BAQUFAAOCAQEARnFIjyitrCGbleFr3KeAwdOyeHiRmgeKupX5ZopgXtcseJoToUIinX5DVw2fVZPahqs0Q7/a0wcVnTRpw6946qZCwKd/PvZ1feVuVEA5Ui3+XvHuSH5xLp7NvYG1snNEvlbN3+NDUMlWj2NEbihowUBt9+UxTpQO3+N08q3aZk3hOZ+tHt+1Te7KEEL/4CM28GZ9MY7fSrS7MAgp1+ZXtn+kRlMrXnQ49qBda37brwDRqmSY9PwNMbev3r+9ZHwxr9W5wXW4Ev4C4xngA7RkVoyDbItSUho0I0M0u/LHuppclnXrw97xyO5Z883eIBvPVjfRcxsJxXJ8jx70ATDskw=="],"kid":"akm5hvbbevE341ovl0h7","kty":"RSA","use":"sig","x5t#S256":"5GOpy9CQVtfvBmu2T8BHvpKE4OGtC3BuS046t7p9pps"}'
    http_version: 
  recorded_at: Thu, 14 Jul 2016 04:25:28 GMT
- request:
    method: post
    uri: https://okta-test.okta.com/api/v1/apps/0oa6nmg6fdvwvoHwR0h7/credentials/keys/generate
    body:
      encoding: UTF-8
      string: '{"query":{"validityYears":"1"}}'
    headers:
      User-Agent:
      - Oktakit v0.1.0
      Accept:
      - application/json
      Content-Type:
      - application/json
      Authorization:
      - SSWS  <<ACCESS_TOKEN>>
  response:
    status:
      code: 401
      message: 
    headers:
      date:
      - Thu, 14 Jul 2016 19:01:25 GMT
      server:
      - nginx
      content-type:
      - application/json
      x-okta-request-id:
      - V4fhhF7EElb5Qa3d1m2dQwAACJY
      x-rate-limit-limit:
      - '1200'
      x-rate-limit-remaining:
      - '1199'
      x-rate-limit-reset:
      - '1468522945'
      p3p:
      - CP="HONK"
      www-authenticate:
      - SSWS
      set-cookie:
      - sid=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/, JSESSIONID=A057F703903068286DE8542533347951;
        Path=/
      connection:
      - close
      transfer-encoding:
      - chunked
    body:
      encoding: UTF-8
      string: '{"errorCode":"E0000011","errorSummary":"Invalid token provided","errorLink":"E0000011","errorId":"oaeo_ZbVuY9TV-lzcv4sura3g","errorCauses":[]}'
    http_version: 
  recorded_at: Thu, 14 Jul 2016 19:01:25 GMT
- request:
    method: post
    uri: https://okta-test.okta.com/api/v1/apps/0oa6nmg6fdvwvoHwR0h7/credentials/keys/generate?query%5BvalidityYears%5D=1
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Oktakit v0.1.0
      Accept:
      - application/json
      Content-Type:
      - application/json
      Authorization:
      - SSWS  <<ACCESS_TOKEN>>
  response:
    status:
      code: 401
      message: 
    headers:
      date:
      - Thu, 14 Jul 2016 19:54:16 GMT
      server:
      - nginx
      content-type:
      - application/json
      x-okta-request-id:
      - V4ft6OeutR4DI8vky1VpFAAAALI
      x-rate-limit-limit:
      - '1200'
      x-rate-limit-remaining:
      - '1193'
      x-rate-limit-reset:
      - '1468526057'
      p3p:
      - CP="HONK"
      www-authenticate:
      - SSWS
      set-cookie:
      - sid=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/, JSESSIONID=83740D9F182D34D41A5E27A6CEE9443B;
        Path=/
      connection:
      - close
      transfer-encoding:
      - chunked
    body:
      encoding: UTF-8
      string: '{"errorCode":"E0000011","errorSummary":"Invalid token provided","errorLink":"E0000011","errorId":"oaeU2zytNLPRIifKb5K9eeMbQ","errorCauses":[]}'
    http_version: 
  recorded_at: Thu, 14 Jul 2016 19:54:16 GMT
recorded_with: VCR 2.9.3
