---
http_interactions:
- request:
    method: get
    uri: https://okta-test.okta.com/api/v1/apps/0oa6nmg6fdvwvoHwR0h7/credentials/keys/akm5hvbbevE341ovl0h7
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Oktakit v0.1.0
      Accept:
      - application/json
      Content-Type:
      - application/json
      Authorization:
      - SSWS  <<ACCESS_TOKEN>>
  response:
    status:
      code: 200
      message: 
    headers:
      date:
      - Thu, 14 Jul 2016 03:45:57 GMT
      server:
      - nginx
      content-type:
      - application/json
      x-okta-request-id:
      - V4cK9eXAfLU1ttNceQftMAAAA24
      x-rate-limit-limit:
      - '1200'
      x-rate-limit-remaining:
      - '1179'
      x-rate-limit-reset:
      - '1468468011'
      p3p:
      - CP="HONK"
      cache-control:
      - no-cache, no-store
      pragma:
      - no-cache
      expires:
      - '0'
      set-cookie:
      - sid=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/, JSESSIONID=D21685E6B8A37C309FB0BFF2DE502CF0;
        Path=/
      connection:
      - close
      transfer-encoding:
      - chunked
    body:
      encoding: UTF-8
      string: '{"created":"2015-12-10T18:56:23.000Z","expiresAt":"2017-12-10T18:56:22.000Z","x5c":["MIIDqDCCApCgAwIBAgIGAVGNQFX5MA0GCSqGSIb3DQEBBQUAMIGUMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEWMBQGA1UEBwwNU2FuIEZyYW5jaXNjbzENMAsGA1UECgwET2t0YTEUMBIGA1UECwwLU1NPUHJvdmlkZXIxFTATBgNVBAMMDGJhbGFjb21wdGVzdDEcMBoGCSqGSIb3DQEJARYNaW5mb0Bva3RhLmNvbTAeFw0xNTEyMTAxODU1MjJaFw0xNzEyMTAxODU2MjJaMIGUMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEWMBQGA1UEBwwNU2FuIEZyYW5jaXNjbzENMAsGA1UECgwET2t0YTEUMBIGA1UECwwLU1NPUHJvdmlkZXIxFTATBgNVBAMMDGJhbGFjb21wdGVzdDEcMBoGCSqGSIb3DQEJARYNaW5mb0Bva3RhLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJJjrcnI6cXBiXNq9YDgfYrQe2O5qEHG4MXP8Ue0sMeefFkFEHYHnHUeZCq6WTAGqR+1LFgOl+Eq9We5V+qNlGIfkFkQ3iHGBrIALKqLCd0Et76HicDiegz7j9DtN+lo0hG/gfcw5783L5g5xeQ7zVmCQMkFwoUA0uA3bsfUSrmfORHJL+EMNQT8XIXD8NkG4g6u7ylHVRTLgXbe+W/p04m3EP6l41xl+MhIpBaPxDsyUvcKCNwkZN3aZIin1O9Y4YJuDHxrM64/VtLLp0sC05iawAmfsLunF7rdJAkWUpPn+xkviyNQ3UpvwAYuDr+jKLUdh2reRnm1PezxMIXzBVMCAwEAATANBgkqhkiG9w0BAQUFAAOCAQEARnFIjyitrCGbleFr3KeAwdOyeHiRmgeKupX5ZopgXtcseJoToUIinX5DVw2fVZPahqs0Q7/a0wcVnTRpw6946qZCwKd/PvZ1feVuVEA5Ui3+XvHuSH5xLp7NvYG1snNEvlbN3+NDUMlWj2NEbihowUBt9+UxTpQO3+N08q3aZk3hOZ+tHt+1Te7KEEL/4CM28GZ9MY7fSrS7MAgp1+ZXtn+kRlMrXnQ49qBda37brwDRqmSY9PwNMbev3r+9ZHwxr9W5wXW4Ev4C4xngA7RkVoyDbItSUho0I0M0u/LHuppclnXrw97xyO5Z883eIBvPVjfRcxsJxXJ8jx70ATDskw=="],"kid":"akm5hvbbevE341ovl0h7","kty":"RSA","use":"sig","x5t#S256":"5GOpy9CQVtfvBmu2T8BHvpKE4OGtC3BuS046t7p9pps"}'
    http_version: 
  recorded_at: Thu, 14 Jul 2016 03:45:57 GMT
recorded_with: VCR 2.9.3
