---
http_interactions:
- request:
    method: get
    uri: https://okta-test.okta.com/api/v1/groups/00g6o0uh8xcL5WbyZ0h7/apps
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Oktakit v0.1.0
      Accept:
      - application/json
      Content-Type:
      - application/json
      Authorization:
      - SSWS  <<ACCESS_TOKEN>>
  response:
    status:
      code: 200
      message: 
    headers:
      date:
      - Thu, 14 Jul 2016 13:20:15 GMT
      server:
      - nginx
      content-type:
      - application/json;charset=UTF-8
      vary:
      - Accept-Encoding
      x-okta-request-id:
      - V4eRj7r8O12L419F@fntZgAAA50
      x-rate-limit-limit:
      - '1200'
      x-rate-limit-remaining:
      - '1198'
      x-rate-limit-reset:
      - '1468502475'
      p3p:
      - CP="HONK"
      cache-control:
      - no-cache, no-store
      pragma:
      - no-cache
      expires:
      - '0'
      link:
      - <https://okta-test.okta.com/api/v1/groups/00g6o0uh8xcL5WbyZ0h7/apps?limit=20>;
        rel="self"
      strict-transport-security:
      - max-age=315360000
      set-cookie:
      - sid=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/, JSESSIONID=0E923BBD6E15B3CB12CABC66FDE652C7;
        Path=/
      connection:
      - close
      transfer-encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: "[]"
    http_version: 
  recorded_at: Thu, 14 Jul 2016 13:20:15 GMT
recorded_with: VCR 3.0.3
