inherit_from: http://shopify.github.io/ruby-style-guide/rubocop.yml

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - bin/*
    - db/schema.rb
    - node_modules/**/*

Rails:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/WordArray:
  MinSize: 2

Metrics/LineLength:
  Enabled: false
