name: Fetch Repositories

on:
  workflow_call:

jobs:
  fetch-repos:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch repository list from Shopify organization
      run: |
        PAGE=1
        while true; do
          echo "Fetching page $PAGE"
          RESPONSE=$(curl -s -D - "https://api.github.com/orgs/shopify/repos?page=$PAGE&per_page=100" -o "repos_page_$PAGE.json")
          if [ "$(jq 'length' repos_page_$PAGE.json)" -eq "0" ]; then
            break
          fi
          jq -r '.[].name' repos_page_$PAGE.json >> repo_list.txt
          LINK_HEADER=$(echo "$RESPONSE" | grep '^Link:' | sed 's/^Link: //')
          if [[ "$LINK_HEADER" != *rel=\"next\"* ]]; then
            break
          fi
          PAGE=$((PAGE + 1))
        done

    - name: Upload repo_list.txt
      uses: actions/upload-artifact@v2
      with:
        name: repo_list
        path: repo_list.txt
