name: Fetch Repositories

on:
  workflow_call:

jobs:
  fetch-repos:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch repository list from Shopify organization
      run: |
        for PAGE in {1..12}; do
          curl -s "https://api.github.com/orgs/shopify/repos?page=$PAGE&per_page=100" | jq -r '.[].name' >> repo_list.txt
        done

    - name: Upload repo_list.txt
      uses: actions/upload-artifact@v2
      with:
        name: repo_list
        path: repo_list.txt
