language: go
go:
  - "1.7.1"
ruby:
  - "2.3.1"
install:
  - go get github.com/constabulary/gb/...
  - gb vendor restore
script:
  - gb test
  - gb build all
deploy:
  provider: script
  skip_cleanup: true
  script: bundle install && ./script/build_deb
  on:
    branch: master
