# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 886ed35a39c49be084f770453a59adb9914f1d4d265f1c8ba6912e7afe55279a428f65e1a9baf3725858e61d999610335cb103e082d9b3c5b7a79aff199b2524

test:
  secret_key_base: c0df2e97e6421442e6ee88713d0c096e59157ce33c9c36257c743a74d94b1c7f6c7ad96127096c5232e3639b033b8d3c65e256e2f6fe1de3607802ca2049558a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
